config/routes.rb
Rails.application.routes.draw do
  get 'trainings/new'

  get 'work_structures/new'

  get 'users/index'

  get 'hours' => 'employees#hours'
  post 'hours' => 'employees#hours'

  root 'home#index'
  resources :employees do
    resources :educations
    resources :work_exps
    resources :dependants
    resources :abilities
    resources :employee_abilities
    resources :trainings
    resources :training_employees
    resources :hours
  end

  resources :institutions do
    resources :trainings
    resources :instructors
  end

  resources :trainings do
    resources :employees
    resources :training_employees
  end

  resources :training_employees

  resources :work_structures do
    resources :work_structure_abilities
    resources :abilities
  end

  resources :abilities do
    resources :work_structure_abilities
    resources :work_structures
    resources :employees_abilities
    resources :employees
  end

  resources :users
  get 'test', to: "employees#test"
  get 'suprimir', to: "employees#suprimir"
  get 'reactivar', to: "employees#reactivar"
  get 'comparacion', to: "employees#comparacion"
  post '/employees/:employee_id', to: "employees#hours_show"

  get "/bonoEducativo" => "employees#bonoEducativo"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :employee_abilities
	has_many :employees, :through => :employee_abilities

  has_many :work_structure_abilities
  has_many :work_structures, :through => :work_structure_abilities
end

app/models/dependant.rb
class Dependant < ActiveRecord::Base
  belongs_to :employee
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :employee
	mount_uploader :constancia, ConstanciaUploader
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates_uniqueness_of :work_id, :name
	validates_numericality_of :work_id, greater_than:0
	validates_numericality_of :emergency_contact_number, greater_than:0
	mount_uploader :avatar, AvatarUploader

	has_many :educations
	has_many :work_exps
	has_many :dependants
	has_many :employee_abilities
	has_many :abilities, :through => :employee_abilities
	belongs_to :work_structure
	has_many :training_employees
  has_many :trainings, :through => :training_employees
	has_many :hours

  def self.civil_statuses
    ["Soltero", "Casado", "Viudo", "Divorciado", "Union Libre"];
  end

  def self.bloods
    ["O-", "O" , "A-", " A+" ,"B-", " B+" , "AB-", " AB+"]
  end

	def self.contracts
    ["Permanente", "Temporal" , "Practicante"]
  end

	def self.parentesco
    ["Hijo", "Conyuge", "Hermano"]
  end

	def self.habilidades
		["Ejemplo1", "Ejemplo2", "Ejemplo3"]
	end

	def self.age(dob)
		now = Time.now.utc.to_date
		now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
	end


	def self.TieneHijosMenoresW
		employees = Employee.all
		employees.each do |e|
			if e.dependants.any?
				e.dependants.each do |d|
					if(d.birth_at != nil)
						if age(d.birth_at) < 18
							e.hasChildren = true
						end
					else
						e.hasChildren = false
					end
				end
			end
			e.save!
		end
	end

	def get_hours(time_in, time_out)
		hours = Hash.new
		hours["normal"] = 0
		hours["25"] = 0
		hours["50"] = 0
		hours["75"] = 0
		hours["100"] = 0
		self.hours.where(time_in: time_in.in_time_zone("UTC").beginning_of_day..time_out.in_time_zone("UTC").end_of_day).each do |h|
			(h.time_in.to_i .. h.time_out.to_i).step(1.hour) do |x|
				hours["normal"] += ((h.time_in.change(hour:8)..h.time_out.change(hour:17)).cover?(Time.at(x)) ? 1 : 0)
				hours["25"] += ((h.time_in.change(hour:17)..h.time_out.change(hour:21)).cover?(Time.at(x)) ? 1 : 0)
				hours["50"] += ((h.time_in.change(hour:21)..h.time_out.change(hour:0)).cover?(Time.at(x)) ? 1 : 0)
				hours["75"] += ((h.time_in.change(hour:4)..h.time_out.change(hour:8)).cover?(Time.at(x)) ? 1 : 0)
				hours["100"] += ((h.time_in.change(hour:0)..h.time_out.change(hour:4)).cover?(Time.at(x)) ? 1 : 0)
			end
		end
		return hours
	end


end

app/models/employee_ability.rb
class EmployeeAbility < ActiveRecord::Base
  belongs_to :employee
  belongs_to :ability
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :employee
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :trainings
  has_many :instructors
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :institution
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_employees
  has_many :employees, :through => :training_employees

  belongs_to :institution

  def self.categories
    ["Capacitacion", "Charla", "Seminario", "Taller"];
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password validations: false

	validates_presence_of :email, :password
	validates :email, uniqueness: true
end

app/models/work_exp.rb
class WorkExp < ActiveRecord::Base
  belongs_to :employee
  mount_uploader :constancia, ConstanciaUploader
end

app/models/work_place.rb
class WorkPlace < ActiveRecord::Base
end

app/models/work_structure.rb
class WorkStructure < ActiveRecord::Base
  has_many :employees
  has_many :work_structure_abilities
  has_many :abilities, :through => :work_structure_abilities
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    @trainingplanned = Training.where("start_date >= ? AND planned = true",Time.now).order(:start_date)
    @trainingbefore = Training.where("start_date < ?",Time.now).order(:start_date)
    @trainingnotplanned = Training.where("start_date >= ? AND planned = false",Time.now).order(:start_date)
  end

  def new
  	@training = Training.new
    @training_employee = @training.training_employees.build
  end

  def create
    @training = Training.new(training_params)

    if @training.save
      redirect_to @training
    else
      render :new
    end
  end


  def show
      @training = Training.find(params[:id])
      @training_employee = @training.training_employees.build
    end


  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])

    if @training.update_attributes(training_params)
      redirect_to trainings_path
    else
      render :edit
    end
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path
  end

  protected

  def training_params
    params.require(:training).permit!
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_exps_helper.rb
module WorkExpsHelper
end

app/views/trainings/_form.html.erb
<div class="x_content">
  <br />
  <div style="width: 48%; float: left">
  <div class="form-group">
    <%= f.label :training_name, "Nombre" %>
    <%= f.text_field :training_name, class: "form-control", placeholder: "Nombre de la capacitacion" %>
  </div>

  <div class="form-group">
    <%= f.label :start_date, "Fecha de Inicio" %>
    <%= f.date_field :start_date, class: "form-control", placeholder: "Duracion total en Horas" %>
  </div>

  <div class="form-group">
    <%= f.label :category, "Categoria" %>
    <%= f.select :category, Training.categories, {}, class: "form-control"%>
  </div>

</div>
<div style="width: 48%; float: right">
  <div class="form-group">
    <%= f.label :institution_id, "Institucion a Cargo" %>
    <%= f.select(:institution_id, options_for_select(Institution.all.pluck(:name, :id)))%>
  </div>

  <div class="form-group">
    <%= f.label :duration, "Duracion" %>
    <%= f.number_field :duration, class: "form-control", placeholder: "Duracion total en Horas" %>
  </div>

  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Capacitacion planeada?</label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div id="planned" class="btn-group" data-toggle="buttons">
        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
            <%= f.radio_button :planned, true %> &nbsp; Si &nbsp;
        </label>
        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
          <%= f.radio_button :planned, false %> No
        </label>
      </div>
    </div>
  </div>

</div>
<br>
</div>

app/views/trainings/edit.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Editar Capacitacion</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>
          <%= render partial: "partials/errors", locals: { obj: @training } %>
          <%= form_for @training do |f| %>
            <%= render partial: "form", locals: {f: f} %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", trainings_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Actualizar" , class: "btn btn-success"%>
              </div>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainings/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>HonduCaribe</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel" style="height:600px; width: 100%">
              <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Capacitaciones Pasadas</a>
                  </li>
                  <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Capacitaciones Planeadas</a>
                  </li>
                  <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Capacitaciones Extras</a>
                  </li>
                </ul>
                <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">

                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <div style="float: center; border-left: 500px">
                      <table class="table table-hover">
                        <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
                          <tr>
                            <th>Codigo  </th>
                            <th>Nombre de Capacitacion</th>
                            <th>Instructor</th>
                            <th>Fecha de Inicio</th>
                            <th>Duracion</th>
                            <th>Acciones</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%- @trainingbefore.each do |f| %>
                            <tr>
                              <td><%= f.id %></td>
                              <td><%= link_to f.training_name, training_path(f) %></td>
                              <td>
                                <% if(Instructor.find_by(id: f.instructor_id)) %>
                                  <%= Instructor.find(f.instructor_id).name %>
                                <%end%>
                              </td>
                              <td><%= nice_date(f.start_date) %></td>
                              <td><%= f.duration %></td>
                              <th>
                                <%= link_to edit_training_path(f.id, f), class: "btn btn-success" do %>
                                  <i class="fa fa-edit m-right-xs"></i> Editar
                                <% end %>

                                <%= link_to "Eliminar", f, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger" %>
                              </th>

                            </tr>
                          <%- end %>
                        </tbody>
                      </table>
                    </div>
                  </div>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab" style="text-align: center">

                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <div style="float: center; border-left: 500px">
                      <table class="table table-hover">
                        <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
                          <tr>
                            <th>Codigo  </th>
                            <th>Nombre de Capacitacion</th>
                            <th>Instructor</th>
                            <th>Fecha de Inicio</th>
                            <th>Duracion</th>
                            <th>Acciones</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%- @trainingplanned.each do |f| %>
                            <tr>
                              <td><%= f.id %></td>
                              <td><%= link_to f.training_name, training_path(f) %></td>
                              <td>
                                <% if(Instructor.find_by(id: f.instructor_id)) %>
                                  <%= Instructor.find(f.instructor_id).name %>
                                <%end%>
                              </td>
                              <td><%= nice_date(f.start_date) %></td>
                              <td><%= f.duration %></td>
                              <th>
                                <%= link_to edit_training_path(f.id, f), class: "btn btn-success" do %>
                                  <i class="fa fa-edit m-right-xs"></i> Editar
                                <% end %>

                                <%= link_to "Eliminar", f, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger" %>
                              </th>

                            </tr>
                          <%- end %>
                        </tbody>
                      </table>
                    </div>
                  </div>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab" style="text-align: center">

                  <div class="col-md-12 col-sm-12 col-xs-12">
                    <div style="float: center; border-left: 500px">
                      <table class="table table-hover">
                        <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
                          <tr>
                            <th>Codigo  </th>
                            <th>Nombre de Capacitacion</th>
                            <th>Instructor</th>
                            <th>Fecha de Inicio</th>
                            <th>Duracion</th>
                            <th>Acciones</th>
                          </tr>
                        </thead>
                        <tbody>
                          <%- @trainingnotplanned.each do |f| %>
                            <tr>
                              <td><%= f.id %></td>
                              <td><%= link_to f.training_name, training_path(f) %></td>
                              <td>
                                <% if(Instructor.find_by(id: f.instructor_id)) %>
                                  <%= Instructor.find(f.instructor_id).name %>
                                <%end%>
                              </td>
                              <td><%= nice_date(f.start_date) %></td>
                              <td><%= f.duration %></td>
                              <th>
                                <%= link_to edit_training_path(f.id, f), class: "btn btn-success" do %>
                                  <i class="fa fa-edit m-right-xs"></i> Editar
                                <% end %>

                                <%= link_to "Eliminar", f, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger" %>
                              </th>

                            </tr>
                          <%- end %>
                        </tbody>
                      </table>
                    </div>
                  </div>


                  </div>
                </div>
              </div>
            </div>
            </div>


    </div>
  </div>
</div>

app/views/trainings/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nuevo Empleado</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>
          <%= render partial: "partials/errors", locals: { obj: @training } %>
          <%= form_for @training do |f| %>
            <%= render partial: "form", locals: {f: f} %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", trainings_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Crear" , class: "btn btn-success"%>
              </div>
            </div>
          <%- end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/trainings/show.html.erb
<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>User Profile</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                      <h3><%=@training.training_name%></h3>

                      <ul class="list-unstyled user_data">
                        <li>
                           <%= @training.duration%> horas
                        </li>
                        <li>
                           <%= nice_date(@training.start_date) %>
                        </li>
                        <% if(Institution.find_by_id(@training.institution_id)) %>
                        <li>
                           <%= Institution.find_by_id(@training.institution_id).name%>
                        </li>
                        <%end%>
                        <% if(Instructor.find_by_id(@training.instructor_id)) %>
                        <li>
                           <%= Instructor.find_by_id(@training.instructor_id).name %>, <%= Instructor.find_by_id(@training.instructor_id).phone %>, <%= Instructor.find_by_id(@training.instructor_id).email %>
                        </li>
                        <%end%>
                      </ul>
                        <% if(!Instructor.find_by_id(@training.instructor_id)) %>
                      <%= link_to edit_training_path(@training), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#addInstructor', class: "btn btn-success"} do %>
                        <i class="fa fa-edit m-right-xs"></i> Anadir Instructor
                      <% end %>
                      <%end%>


                      <br />


                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                      <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                          <li role="presentation"><a href="#tab_content2" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Empleados</a>
                          </li>
                        </ul>

                        <div id="myTabContent" class="tab-content">
                          <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="home-tab" style="text-align: center">

                            <% if @training.employees.any? %>
                              <table class="data table table-striped no-margin" style="text-align: center; width: 100%">
                                <thead>
                                  <tr>
                                    <th style= "text-align: center">Codigo Empleado</th>
                                    <th style= "text-align: center">Nombre</th>
                                    <th style= "text-align: center">Asistencia</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    <%- @training.employees.each do |f| %>
                                      <tr>
                                        <td><%= f.work_id %></td>
                                        <td><%= link_to f.name, employee_path(f) %></td>
                                        <%if TrainingEmployee.where("training_id = ? AND employee_id = ?", @training.id, f.id).first.asistencia  %>
                                          <td>Asistio</td>
                                        <%else%>
                                          <td>No Asistio</td>
                                        <%end%>

                                        <th>
                                          <%= form_for TrainingEmployee.where("training_id = ? AND employee_id = ?", @training.id, f.id).first, url: training_training_employee_path(@training, TrainingEmployee.where("training_id = ? AND employee_id = ?", @training.id, f.id).first.id) do |f| %>
                                            <%= f.hidden_field :asistencia, value: true %>
                                            <%= f.submit "Confirmar Asistencia", class:"btn btn-success"%>
                                          <% end %>
                                          <%= form_for TrainingEmployee.where("training_id = ? AND employee_id = ?", @training.id, f.id).first, url: training_training_employee_path(@training, TrainingEmployee.where("training_id = ? AND employee_id = ?", @training.id, f.id).first.id) do |f| %>
                                            <%= f.hidden_field :asistencia, value: false %>
                                            <%= f.submit "Confirmar Inasistencia", class:"btn btn-danger"%>
                                          <% end %>
                                        </td>
                                      </trh
                                    <%- end %>
                                </tbody>
                              </table>
                              <% else %>
                                <p><em>No hay Informacion.</em></p>
                              <% end %>
                              <%= link_to new_training_training_employee_path(@training), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#addEmployee', class: "btn btn-success"} do %>
                                <i class="fa fa-edit m-right-xs"></i> Invitar Empleado
                              <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

<div class="modal fade" id="addEmployee" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Invitar Empleado</h4>
      </div>
      <%= form_for [@training, @training_employee] do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :employee_id, "Numero de Empleado" %>
          <%= f.select(:employee_id, options_for_select(Employee.where("employee_status = true").pluck(:name, :id)))%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.submit "Crear" , class: "btn btn-primary"%>
      </div>
      <%- end %>
    </div>
  </div>
</div>

<div class="modal fade" id="addInstructor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Anadir Instructor</h4>
      </div>
      <%= form_for @training do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :instructor_id, "Instructor" %>
          <%= f.select(:instructor_id, options_for_select(Institution.find_by_id(@training.institution_id).instructors.pluck(:name, :id)))%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.submit "Crear" , class: "btn btn-primary"%>
      </div>
      <%- end %>
    </div>
  </div>
</div>