config/routes.rb
Rails.application.routes.draw do
  get 'trainings/new'

  get 'work_structures/new'

  get 'users/index'

  get 'hours' => 'employees#hours'
  post 'hours' => 'employees#hours'

  root 'home#index'
  resources :employees do
    resources :educations
    resources :work_exps
    resources :dependants
    resources :abilities
    resources :employee_abilities
    resources :trainings
    resources :training_employees
    resources :hours
  end

  resources :institutions do
    resources :trainings
    resources :instructors
  end

  resources :trainings do
    resources :employees
    resources :training_employees
  end

  resources :training_employees

  resources :work_structures do
    resources :work_structure_abilities
    resources :abilities
  end

  resources :abilities do
    resources :work_structure_abilities
    resources :work_structures
    resources :employees_abilities
    resources :employees
  end

  resources :users
  get 'test', to: "employees#test"
  get 'suprimir', to: "employees#suprimir"
  get 'reactivar', to: "employees#reactivar"
  get 'comparacion', to: "employees#comparacion"
  post '/employees/:employee_id', to: "employees#hours_show"

  get "/bonoEducativo" => "employees#bonoEducativo"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :employee_abilities
	has_many :employees, :through => :employee_abilities

  has_many :work_structure_abilities
  has_many :work_structures, :through => :work_structure_abilities
end

app/models/dependant.rb
class Dependant < ActiveRecord::Base
  belongs_to :employee
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :employee
	mount_uploader :constancia, ConstanciaUploader
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates_uniqueness_of :work_id, :name
	validates_numericality_of :work_id, greater_than:0
	validates_numericality_of :emergency_contact_number, greater_than:0
	mount_uploader :avatar, AvatarUploader

	has_many :educations
	has_many :work_exps
	has_many :dependants
	has_many :employee_abilities
	has_many :abilities, :through => :employee_abilities
	belongs_to :work_structure
	has_many :training_employees
  has_many :trainings, :through => :training_employees
	has_many :hours

  def self.civil_statuses
    ["Soltero", "Casado", "Viudo", "Divorciado", "Union Libre"];
  end

  def self.bloods
    ["O-", "O" , "A-", " A+" ,"B-", " B+" , "AB-", " AB+"]
  end

	def self.contracts
    ["Permanente", "Temporal" , "Practicante"]
  end

	def self.parentesco
    ["Hijo", "Conyuge", "Hermano"]
  end

	def self.habilidades
		["Ejemplo1", "Ejemplo2", "Ejemplo3"]
	end

	def self.age(dob)
		now = Time.now.utc.to_date
		now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
	end


	def self.TieneHijosMenoresW
		employees = Employee.all
		employees.each do |e|
			if e.dependants.any?
				e.dependants.each do |d|
					if(d.birth_at != nil)
						if age(d.birth_at) < 18
							e.hasChildren = true
						end
					else
						e.hasChildren = false
					end
				end
			end
			e.save!
		end
	end

	def get_hours(time_in, time_out)
		hours = Hash.new
		hours["normal"] = 0
		hours["25"] = 0
		hours["50"] = 0
		hours["75"] = 0
		hours["100"] = 0
		self.hours.where(time_in: time_in.in_time_zone("UTC").beginning_of_day..time_out.in_time_zone("UTC").end_of_day).each do |h|
			(h.time_in.to_i .. h.time_out.to_i).step(1.hour) do |x|
				hours["normal"] += ((h.time_in.change(hour:8)..h.time_out.change(hour:17)).cover?(Time.at(x)) ? 1 : 0)
				hours["25"] += ((h.time_in.change(hour:17)..h.time_out.change(hour:21)).cover?(Time.at(x)) ? 1 : 0)
				hours["50"] += ((h.time_in.change(hour:21)..h.time_out.change(hour:0)).cover?(Time.at(x)) ? 1 : 0)
				hours["75"] += ((h.time_in.change(hour:4)..h.time_out.change(hour:8)).cover?(Time.at(x)) ? 1 : 0)
				hours["100"] += ((h.time_in.change(hour:0)..h.time_out.change(hour:4)).cover?(Time.at(x)) ? 1 : 0)
			end
		end
		return hours
	end


end

app/models/employee_ability.rb
class EmployeeAbility < ActiveRecord::Base
  belongs_to :employee
  belongs_to :ability
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :employee
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :trainings
  has_many :instructors
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :institution
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_employees
  has_many :employees, :through => :training_employees

  belongs_to :institution

  def self.categories
    ["Capacitacion", "Charla", "Seminario", "Taller"];
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password validations: false

	validates_presence_of :email, :password
	validates :email, uniqueness: true
end

app/models/work_exp.rb
class WorkExp < ActiveRecord::Base
  belongs_to :employee
  mount_uploader :constancia, ConstanciaUploader
end

app/models/work_place.rb
class WorkPlace < ActiveRecord::Base
end

app/models/work_structure.rb
class WorkStructure < ActiveRecord::Base
  has_many :employees
  has_many :work_structure_abilities
  has_many :abilities, :through => :work_structure_abilities
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  def index
    @institutions = Institution.all
  end

  def new
  @institution = Institution.new
  end

  def create
  @institution = Institution.new(institution_params)

  if @institution.save
    redirect_to institutions_path,  notice: "Se agrego con exito"
  else
    render :new
  end
end

  def show
   @institution = Institution.find_by_id(params[:id])
   @instructor = @institution.instructors.build
  end


 def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy
    redirect_to institutions_path,  notice: "Se borro con exito companero"
  end



protected

  def institution_params
      params.require(:institution).permit!
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/institutions/_form.html.erb
<div class="x_content">
  <br>
  <div style="width: 48%; float: left">
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre de la Institución" %>
  </div>

  <div class="form-group">
    <%= f.label :email, "Correo" %>
    <%= f.email_field :email, class: "form-control", placeholder: "Correo" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Descripcion" %>
    <%= f.text_field :description, class: "form-control", placeholder: "Descripcion" %>
  </div>

  <div class="form-group">
    <%= f.label :phone, "Telefono" %>
    <%= f.text_field :phone, class: "form-control", placeholder: "Telefono" %>
  </div>

</div>
<br>
</div>

app/views/institutions/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>HonduCaribe</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px; ">
          <div class="x_title">
            <h2>Listado de Instituciones</h2>
            <div class="clearfix"></div>
          </div>
          <div style="float: center; border-left: 500px">
            <table class="table table-hover">
              <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
                <tr>
                  <th>Nombre de Institucion</th>
                  <th>Descripcion</th>
                </tr>
              </thead>
              <tbody>
                <%- @institutions.each do |f| %>
                  <tr>
                    <td><%= link_to f.name, institution_path(f.id) %></td>
                    <td><%= f.description %></td>
                    <th>
                      <%= link_to "Eliminar", f, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger" %>
                    </th>

                  </tr>
                <%- end %>
              </tbody>
            </table>
            <%= link_to new_institution_path, class: "btn btn-success" do %>
              <i class="fa fa-edit m-right-xs"></i> Anadir Institucion
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/institutions/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nueva Institucion</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>

          <%= form_for @institution do |f| %>
            <%= render partial: "form", locals: {f: f} %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", employees_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Crear" , class: "btn btn-success"%>
              </div>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/institutions/show.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= @institution.name %> </h3>
        <h5></h5>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px; ">
          <div class="x_title">
            <h2>Institucion</h2>
            <div class="clearfix"></div>
          </div>
          <div style="float: center; border-left: 500px">
            <h3>Instructores</h3>
            <% if @institution.instructors.any? %>
              <table class="data table table-striped no-margin" style="text-align: center; width: 100%">
                <thead>
                  <tr>
                    <th style= "text-align: center">Nombre</th>
                    <th style= "text-align: center">Correo</th>
                    <th style= "text-align: center">Numero</th>
                    <th style= "text-align: center">Descripcion</th>
                  </tr>
                </thead>
                <tbody>
                  <%- @institution.instructors.each do |f| %>
                    <% if(f) %>
                      <tr>
                        <td><%= f.name %></td>
                        <td><%= f.email %></td>
                        <td><%= f.phone %></td>
                        <td><%= f.description %></td>
                      </tr>
                    <%end%>
                  <%- end %>
                </tbody>
              </table>
              <% else %>
                <p><em>No hay Informacion.</em></p>
              <% end %>
                <%= link_to new_institution_instructor_path(@institution), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#addInstructor', class: "btn btn-success"} do %>
                  <i class="fa fa-edit m-right-xs"></i> Anadir Instructor
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="addInstructor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Anadir Instructor</h4>
      </div>
      <%= form_for [@institution, @instructor] do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Nombre del Instructor" %>
        </div>

        <div class="form-group">
          <%= f.label :email, "Correo" %>
          <%= f.email_field :email, class: "form-control", placeholder: "Correo" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Descripcion" %>
          <%= f.text_field :description, class: "form-control", placeholder: "Descripcion" %>
        </div>

        <div class="form-group">
          <%= f.label :phone, "Telefono" %>
          <%= f.text_field :phone, class: "form-control", placeholder: "Telefono" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= f.submit "Crear" , class: "btn btn-primary"%>
      </div>
      <%- end %>
    </div>
  </div>
</div>