config/routes.rb
Rails.application.routes.draw do
  get 'trainings/new'

  get 'work_structures/new'

  get 'users/index'

  get 'hours' => 'employees#hours'
  post 'hours' => 'employees#hours'

  root 'home#index'
  resources :employees do
    resources :educations
    resources :work_exps
    resources :dependants
    resources :abilities
    resources :employee_abilities
    resources :trainings
    resources :training_employees
    resources :hours
  end

  resources :institutions do
    resources :trainings
    resources :instructors
  end

  resources :trainings do
    resources :employees
    resources :training_employees
  end

  resources :training_employees

  resources :work_structures do
    resources :work_structure_abilities
    resources :abilities
  end

  resources :abilities do
    resources :work_structure_abilities
    resources :work_structures
    resources :employees_abilities
    resources :employees
  end

  resources :users
  get 'test', to: "employees#test"
  get 'suprimir', to: "employees#suprimir"
  get 'reactivar', to: "employees#reactivar"
  get 'comparacion', to: "employees#comparacion"
  post '/employees/:employee_id', to: "employees#hours_show"

  get "/bonoEducativo" => "employees#bonoEducativo"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :employee_abilities
	has_many :employees, :through => :employee_abilities

  has_many :work_structure_abilities
  has_many :work_structures, :through => :work_structure_abilities
end

app/models/dependant.rb
class Dependant < ActiveRecord::Base
  belongs_to :employee
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :employee
	mount_uploader :constancia, ConstanciaUploader
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates_uniqueness_of :work_id, :name
	validates_numericality_of :work_id, greater_than:0
	validates_numericality_of :emergency_contact_number, greater_than:0
	mount_uploader :avatar, AvatarUploader

	has_many :educations
	has_many :work_exps
	has_many :dependants
	has_many :employee_abilities
	has_many :abilities, :through => :employee_abilities
	belongs_to :work_structure
	has_many :training_employees
  has_many :trainings, :through => :training_employees
	has_many :hours

  def self.civil_statuses
    ["Soltero", "Casado", "Viudo", "Divorciado", "Union Libre"];
  end

  def self.bloods
    ["O-", "O" , "A-", " A+" ,"B-", " B+" , "AB-", " AB+"]
  end

	def self.contracts
    ["Permanente", "Temporal" , "Practicante"]
  end

	def self.parentesco
    ["Hijo", "Conyuge", "Hermano"]
  end

	def self.habilidades
		["Ejemplo1", "Ejemplo2", "Ejemplo3"]
	end

	def self.age(dob)
		now = Time.now.utc.to_date
		now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
	end


	def self.TieneHijosMenoresW
		employees = Employee.all
		employees.each do |e|
			if e.dependants.any?
				e.dependants.each do |d|
					if(d.birth_at != nil)
						if age(d.birth_at) < 18
							e.hasChildren = true
						end
					else
						e.hasChildren = false
					end
				end
			end
			e.save!
		end
	end

	def get_hours(time_in, time_out)
		hours = Hash.new
		hours["normal"] = 0
		hours["25"] = 0
		hours["50"] = 0
		hours["75"] = 0
		hours["100"] = 0
		self.hours.where(time_in: time_in.in_time_zone("UTC").beginning_of_day..time_out.in_time_zone("UTC").end_of_day).each do |h|
			(h.time_in.to_i .. h.time_out.to_i).step(1.hour) do |x|
				hours["normal"] += ((h.time_in.change(hour:8)..h.time_out.change(hour:17)).cover?(Time.at(x)) ? 1 : 0)
				hours["25"] += ((h.time_in.change(hour:17)..h.time_out.change(hour:21)).cover?(Time.at(x)) ? 1 : 0)
				hours["50"] += ((h.time_in.change(hour:21)..h.time_out.change(hour:0)).cover?(Time.at(x)) ? 1 : 0)
				hours["75"] += ((h.time_in.change(hour:4)..h.time_out.change(hour:8)).cover?(Time.at(x)) ? 1 : 0)
				hours["100"] += ((h.time_in.change(hour:0)..h.time_out.change(hour:4)).cover?(Time.at(x)) ? 1 : 0)
			end
		end
		return hours
	end


end

app/models/employee_ability.rb
class EmployeeAbility < ActiveRecord::Base
  belongs_to :employee
  belongs_to :ability
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :employee
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :trainings
  has_many :instructors
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :institution
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_employees
  has_many :employees, :through => :training_employees

  belongs_to :institution

  def self.categories
    ["Capacitacion", "Charla", "Seminario", "Taller"];
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password validations: false

	validates_presence_of :email, :password
	validates :email, uniqueness: true
end

app/models/work_exp.rb
class WorkExp < ActiveRecord::Base
  belongs_to :employee
  mount_uploader :constancia, ConstanciaUploader
end

app/models/work_place.rb
class WorkPlace < ActiveRecord::Base
end

app/models/work_structure.rb
class WorkStructure < ActiveRecord::Base
  has_many :employees
  has_many :work_structure_abilities
  has_many :abilities, :through => :work_structure_abilities
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def hours_show
    respond_to do |format|
      format.html
      format.js { render "hours_show", locals: {employee: Employee.find(params[:employee_id]), from: params[:report][:from], to: params[:report][:to]}}
    end
  end

  def hours
    @employees = Employee.where(employee_status: true)

    respond_to do |format|
      format.html
      format.js { render "hours", locals: {employee: Employee.where(employee_status: true), time_in: params[:report][:from], time_out: params[:report][:to]}}
    end

  end

  def index
    @employees = Employee.where("employee_status = true")
    @inactiveemployees = Employee.where("employee_status = false")
    query = params[:q]
    if query
      @employees = @employees.where("name LIKE '%#{query}%'")
    end

    if request.xhr?
      render partial: "table", locals: {employees: @employees}, status: 200
    end
  end

  def show
    @employee = Employee.find(params[:id])
    @education = @employee.educations.build
    @work_exp = @employee.work_exps.build
    @ability =  @employee.abilities.build
    @dependant =  @employee.dependants.build
    @work_structures = WorkStructure.all
    @employee_ability = @employee.employee_abilities.build
    @hour = @employee.hours.build
  end

  def new
    @employee = Employee.new
    @employee.avatar = params[:file]
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.RAP_code = @employee.identity_number

    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.RAP_code = @employee.identity_number


    if @employee.update_attributes(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  def comparacion
    @employee = Employee.find(params[:id])
  end

  def test

  end

  def suprimir
    @employee = Employee.find(params[:id])
  end

  def bonoEducativo
    @employees = Employee.all

  end

  def reactivar
    @employee = Employee.find(params[:id])
    if @employee.update_column(:employee_status, true)
      redirect_to employees_path
    else
      redirect_to employee_path(@employee)
    end
  end

  protected

    def employee_params
      params.require(:employee).permit!
    end

end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/work_exps_helper.rb
module WorkExpsHelper
end

app/views/employees/BonoEducativo.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>HonduCaribe</h3>
      </div>



      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <%= form_tag employees_path, remote: true, method: :get, class: "js-employees-filter form-inline" do %>
              <%= text_field_tag :q, params[:q], placeholder: "Buscar...", class: "form-control", display: "inline-block" %>
                <%= button_tag type: "submit", class: "btn btn-default", display: "inline-block" do %>
                  <span class="input-group-btn"> Ir! </span>
                <%end%>
      	   <% end %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px; ">
          <div class="x_title">
            <h2>Empleados con hijos menores de 18</h2>
            <div class="clearfix"></div>
          </div>
          <div style="float: center; border-left: 500px">
            <div class="js-employees-table">
              <%= render partial: "table", locals: { employees: @employees} %>
            </div>
          </div>
          <%= link_to "Cancelar", employees_path%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/_form.html.erb
              <div class="x_content">
                <br />
                <div style="width: 48%; float: left">
                <div class="form-group">
                  <%= f.label :name, "Nombre" %>
                  <%= f.text_field :name, class: "form-control", placeholder: "Su Nombre" %>
                </div>
                <div class="form-group">
                  <%= f.label :profession, "Profesion" %>
                  <%= f.text_field :profession, class: "form-control", placeholder: "Profesion" %>
                </div>
                <div class="form-group">
                  <%= f.label :email, "Correo" %>
                  <%= f.email_field :email, class: "form-control", placeholder: "Correo" %>
                </div>
                <div class="form-group">
                  <%= f.label :cellphone, "Telefono" %>
                  <%= f.number_field :cellphone, class: "form-control", placeholder: "Telefono" %>
                </div>
                <div class="form-group">
                  <%= f.label :birth_at, "Fecha de Nacimiento" %>
                  <%= f.date_field :birth_at, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :birth_place, "Lugar de nacimiento" %>
                  <%= f.text_field :birth_place, class: "form-control", placeholder: "birth_place" %>
                </div>
                <div class="form-group">
                  <%= f.label :work_id, "Codigo de Empleado" %>
                  <%= f.number_field :work_id, class: "form-control", placeholder: "Codigo Empleado" %>
                </div>
                <div class="form-group">
                  <%= f.label :date_admission, "Fecha de admision" %>
                  <%= f.date_field :date_admission, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :RAP_code, "Codigo de RAP" %>
                  <%= f.text_field :RAP_code, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :salary, "Salario" %>
                  <%= f.number_field :salary, class: "form-control" %>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Genero</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <div id="gender" class="btn-group" data-toggle="buttons">
                      <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                          <%= f.radio_button :gender, "Hombre" %> &nbsp; Masculino &nbsp;
                      </label>
                      <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                        <%= f.radio_button :gender, "Mujer" %> Femenino
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div style="width: 48%; float: right">
                <div class="form-group">
                  <%= f.label :address, "Direccion" %>
                  <%= f.text_field :address, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :identity_number, "Numero de Cedula" %>
                  <%= f.number_field :identity_number, class: "form-control", placeholder: "Numero de Cedula" %>
                </div>
                <div class="form-group">
                  <%= f.label :base_belong, "Base a la que pertenece" %>
                  <%= f.text_field :base_belong, class: "form-control", placeholder: "Base" %>
                </div>
                <div class="form-group">
                  <%= f.label :contract_type, "Tipo de Contrato" %>
                  <%= f.select :contract_type, Employee.contracts, {}, class: "form-control"%>
                </div>
                <div class="form-group">
                  <%= f.label :civil_status, "Estado Civil: " %>
                  <%= f.select :civil_status, Employee.civil_statuses, {}, class: "form-control"%>
                </div>
                <div class="form-group">
                  <%= f.label :bank_account, "Cuenta de Banco" %>
                  <%= f.number_field :bank_account, class: "form-control", placeholder: "Cuenta de Banco" %>
                </div>
                  <%= f.hidden_field :employee_status, value: true %>
                <div class="form-group">
                  <%= f.label :blood_type, "Tipo de Sangre " %>
                  <%= f.select :blood_type, Employee.bloods, {}, class: "form-control"%>
                </div>
                <div class="form-group">
                  <%= f.label :emergency_contact_name, "Contacto de emergencia" %>
                  <%= f.text_field :emergency_contact_name, class: "form-control", placeholder: "Nombre De Contacto" %>
                </div>
                <div class="form-group">
                  <%= f.label :emergency_contact_number, "Contacto de emergencia" %>
                  <%= f.number_field :emergency_contact_number, class: "form-control", placeholder: "Numero de Contacto" %>
                </div>
                <div class="form-group">
                  <%= f.label :avatar, "Imagen" %>
                  <%= f.file_field :avatar %>
                </div>


                <div>
                  <%= f.label :work_structure_id, "Puesto" %>
                  <%= f.select(:work_structure_id, options_for_select(WorkStructure.all.pluck(:department, :id)))%>



                </div>
              </div>
              <br>
              </div>

app/views/employees/_hours_show.html.erb
<table class="data table table-striped no-margin" style="text-align: center; width: 100%">
  <thead>
    <tr>
      <th style= "text-align: center">Hora de entrada</th>
      <th style= "text-align: center">Hora de salida</th>
    </tr>
  </thead>
  <tbody>
      <%- employee.hours.each do |f| %>
        <% if (f.time_in..f.time_out).overlaps?(from..to) %>
          <tr>
            <td><%= nice_date_time(f.time_in) %></td>
            <td><%= nice_date_time(f.time_out) %></td>
          </tr>
        <% end %>
      <%- end %>
  </tbody>
</table>
<%= link_to new_employee_hour_path(employee), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#addHours', class: "btn btn-success"} do %>
  <i class="fa fa-edit m-right-xs"></i> Anadir Horas
<% end %>

app/views/employees/_hours_table.html.erb
<table class="table table-hover">
  <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
    <tr>
      <th>Codigo de Empleado</th>
      <th>Nombre</th>
      <th>Normal</th>
      <th>25%</th>
      <th>50%</th>
      <th>75%</th>
      <th>100%</th>
    </tr>
  </thead>
  <tbody>
    <%- employees.each do |f| %>
      <%- hours = f.get_hours(time_in, time_out) %>
      <tr>
        <td><%= f.work_id%></td>
        <td><%= link_to f.name, employee_path(f) %></td>
        <td><%= hours["normal"] %></td>
        <td><%= hours["25"] %></td>
        <td><%= hours["50"] %></td>
        <td><%= hours["75"] %></td>
        <td><%= hours["100"] %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/employees/_table.html.erb
<table class="table table-hover">
  <thead style="font-size: 18px; font-family: Fjalla One, sans-serif; color: #00263D">
    <tr>
      <th>Codigo de Empleado</th>
      <th>Nombre</th>
      <th>Puesto</th>
      <th>Area</th>
    </tr>
  </thead>
  <tbody>
    <%- employees.each do |f| %>
      <tr>
        <td><%= f.work_id%></td>
        <td><%= link_to f.name, employee_path(f) %></td>
        <td>
          <% if(WorkStructure.find(f.work_structure_id)) %>
            <%= WorkStructure.find(f.work_structure_id).department %>
          <%end%>
        </td>
        <td><%= f.base_belong %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/employees/edit.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nuevo Empleado</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>
          <%= render partial: "partials/errors", locals: { obj: @employee } %>
          <%= form_for @employee do |f| %>
            <%= render partial: "form", locals: {f: f} %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", employees_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Actualizar" , class: "btn btn-success"%>
              </div>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/hours.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>HonduCaribe</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <%= form_tag employees_path, remote: true, method: :get, class: "js-employees-filter form-inline" do %>
              <%= text_field_tag :q, params[:q], placeholder: "Buscar...", class: "form-control", display: "inline-block" %>
                <%= button_tag type: "submit", class: "btn btn-default", display: "inline-block" do %>
                  <span class="input-group-btn"> Ir! </span>
                <%end%>
      	   <% end %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-xs-12">
        <div class="x_panel" style="height:600px; ">
          <div class="x_title">
            <h2>Listado de Empleados</h2>
            <div class="clearfix"></div>
          </div>
          <%= form_for(:report, remote: true, html: {id:"date_form", class:"row"}) do |f| %>
            <div class="col-xs-6">
              <%= f.label :from, "Desde: ", class:"col-xs-2" %>
              <%= f.date_field :from, class: "form-control", value: Date.today, class:"col-xs-10", onchange: "$('#date_form').submit();" %>
            </div>
            <div class="col-xs-6">
              <%= f.label :to, "Hasta: ", class:"col-xs-2"%>
              <%= f.date_field :to, class: "form-control", value: Date.today, class:"col-xs-10", onchange: "$('#date_form').submit();" %>
            </div>
          <% end %>
          <div style="float: center; border-left: 500px">
            <div class="js-employees-table" id="table_div">
              <%= render partial: "hours_table", locals: {employees: @employees, time_in: Date.today, time_out: Date.today} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/hours.js.erb
$("#table_div").html("<%= j render partial: 'hours_table', locals: {employees: employees, time_in: time_in, time_out: time_out} %>");
console.log("updated");

app/views/employees/hours_show.js.erb
$("#hours_show").html("<%= j render partial: 'hours_show', locals: {employee: employee, from: from, to: to} %>")

app/views/employees/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>HonduCaribe</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <%= form_tag employees_path, remote: true, method: :get, class: "js-employees-filter form-inline" do %>
              <%= text_field_tag :q, params[:q], placeholder: "Buscar...", class: "form-control", display: "inline-block" %>
                <%= button_tag type: "submit", class: "btn btn-default", display: "inline-block" do %>
                  <span class="input-group-btn"> Ir! </span>
                <%end%>
      	   <% end %>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px; ">
        <div class="" role="tabpanel" data-example-id="togglable-tabs">
          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Empleados Activos</a>
            </li>
            <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Empleados Inactivos</a>
            </li>
          </ul>
          <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div style="float: center; border-left: 800px">
                <div class="js-employees-table">
                  <%= render partial: "table", locals: { employees: @employees} %>
                </div>
              </div>
            </div>
            </div>

            <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab" style="text-align: center">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div style="float: center; border-left: 800px">
                <div class="js-employees-table">
                  <%= render partial: "table", locals: { employees: @inactiveemployees} %>
                </div>
              </div>
            </div>
            </div>

          </div>
        </div>
        <%= link_to "Cancelar", employees_path%>
      </div>

        </div>
    </div>
  </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Nuevo Empleado</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>
          <%= render partial: "partials/errors", locals: { obj: @employee } %>
          <%= form_for @employee do |f| %>
            <%= render partial: "form", locals: {f: f} %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", employees_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Crear" , class: "btn btn-success"%>
              </div>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/suprimir.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Suprimir Empleado</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Ir!</button>
                          </span>
          </div>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:900px;">
          <div class="x_title">
            <h2>Formulario</h2>
            <div class="clearfix"></div>
          </div>
          <%= render partial: "partials/errors", locals: { obj: @employee } %>
          <%= form_for @employee do |f| %>
          <div class="form-group">
            <%= f.label :supression_motive, "Razon" %>
            <%= f.text_area :supression_motive, class: "form-control"%>
          </div>
            <%= f.hidden_field :employee_status, value: false %>
            <%= f.hidden_field :supression_date, value: DateTime.now.to_date %>
            <div class="form-group" style="margin: 0 auto; display: block;">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to "Cancelar", employees_path, class: "btn btn-primary" %>
                <button class="btn btn-primary" type="reset">Reset</button>
                <%= f.submit "Suprimir" , class: "btn btn-danger"%>
              </div>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
</div>