config/routes.rb
Rails.application.routes.draw do
  get 'trainings/new'

  get 'work_structures/new'

  get 'users/index'

  get 'hours' => 'employees#hours'
  post 'hours' => 'employees#hours'

  root 'home#index'
  resources :employees do
    resources :educations
    resources :work_exps
    resources :dependants
    resources :abilities
    resources :employee_abilities
    resources :trainings
    resources :training_employees
    resources :hours
  end

  resources :institutions do
    resources :trainings
    resources :instructors
  end

  resources :trainings do
    resources :employees
    resources :training_employees
  end

  resources :training_employees

  resources :work_structures do
    resources :work_structure_abilities
    resources :abilities
  end

  resources :abilities do
    resources :work_structure_abilities
    resources :work_structures
    resources :employees_abilities
    resources :employees
  end

  resources :users
  get 'test', to: "employees#test"
  get 'suprimir', to: "employees#suprimir"
  get 'reactivar', to: "employees#reactivar"
  get 'comparacion', to: "employees#comparacion"
  post '/employees/:employee_id', to: "employees#hours_show"

  get "/bonoEducativo" => "employees#bonoEducativo"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :employee_abilities
	has_many :employees, :through => :employee_abilities

  has_many :work_structure_abilities
  has_many :work_structures, :through => :work_structure_abilities
end

app/models/dependant.rb
class Dependant < ActiveRecord::Base
  belongs_to :employee
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :employee
	mount_uploader :constancia, ConstanciaUploader
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates_uniqueness_of :work_id, :name
	validates_numericality_of :work_id, greater_than:0
	validates_numericality_of :emergency_contact_number, greater_than:0
	mount_uploader :avatar, AvatarUploader

	has_many :educations
	has_many :work_exps
	has_many :dependants
	has_many :employee_abilities
	has_many :abilities, :through => :employee_abilities
	belongs_to :work_structure
	has_many :training_employees
  has_many :trainings, :through => :training_employees
	has_many :hours

  def self.civil_statuses
    ["Soltero", "Casado", "Viudo", "Divorciado", "Union Libre"];
  end

  def self.bloods
    ["O-", "O" , "A-", " A+" ,"B-", " B+" , "AB-", " AB+"]
  end

	def self.contracts
    ["Permanente", "Temporal" , "Practicante"]
  end

	def self.parentesco
    ["Hijo", "Conyuge", "Hermano"]
  end

	def self.habilidades
		["Ejemplo1", "Ejemplo2", "Ejemplo3"]
	end

	def self.age(dob)
		now = Time.now.utc.to_date
		now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
	end


	def self.TieneHijosMenoresW
		employees = Employee.all
		employees.each do |e|
			if e.dependants.any?
				e.dependants.each do |d|
					if(d.birth_at != nil)
						if age(d.birth_at) < 18
							e.hasChildren = true
						end
					else
						e.hasChildren = false
					end
				end
			end
			e.save!
		end
	end

	def get_hours(time_in, time_out)
		hours = Hash.new
		hours["normal"] = 0
		hours["25"] = 0
		hours["50"] = 0
		hours["75"] = 0
		hours["100"] = 0
		self.hours.where(time_in: time_in.in_time_zone("UTC").beginning_of_day..time_out.in_time_zone("UTC").end_of_day).each do |h|
			(h.time_in.to_i .. h.time_out.to_i).step(1.hour) do |x|
				hours["normal"] += ((h.time_in.change(hour:8)..h.time_out.change(hour:17)).cover?(Time.at(x)) ? 1 : 0)
				hours["25"] += ((h.time_in.change(hour:17)..h.time_out.change(hour:21)).cover?(Time.at(x)) ? 1 : 0)
				hours["50"] += ((h.time_in.change(hour:21)..h.time_out.change(hour:0)).cover?(Time.at(x)) ? 1 : 0)
				hours["75"] += ((h.time_in.change(hour:4)..h.time_out.change(hour:8)).cover?(Time.at(x)) ? 1 : 0)
				hours["100"] += ((h.time_in.change(hour:0)..h.time_out.change(hour:4)).cover?(Time.at(x)) ? 1 : 0)
			end
		end
		return hours
	end


end

app/models/employee_ability.rb
class EmployeeAbility < ActiveRecord::Base
  belongs_to :employee
  belongs_to :ability
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :employee
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :trainings
  has_many :instructors
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :institution
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_employees
  has_many :employees, :through => :training_employees

  belongs_to :institution

  def self.categories
    ["Capacitacion", "Charla", "Seminario", "Taller"];
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password validations: false

	validates_presence_of :email, :password
	validates :email, uniqueness: true
end

app/models/work_exp.rb
class WorkExp < ActiveRecord::Base
  belongs_to :employee
  mount_uploader :constancia, ConstanciaUploader
end

app/models/work_place.rb
class WorkPlace < ActiveRecord::Base
end

app/models/work_structure.rb
class WorkStructure < ActiveRecord::Base
  has_many :employees
  has_many :work_structure_abilities
  has_many :abilities, :through => :work_structure_abilities
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "GentelellaOnRails" %> </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body class="nav-md">
<div class="container body">
  <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

<%= render "partials/sidenav" %>
<%= render "partials/topnav" %>

<%= yield %>

  <%= render "partials/footer" %>
  <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/partials/_errors.html.erb
<%- if obj.errors.any? %>
	<div>
		Por favor corrija los siguientes problemas:
		<ul>
			<%- obj.errors.full_messages.each do |msg| %>

				<li><%= msg %></li>
			<%- end %>
		</ul>
	</div>
<% end %>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    UNITEC - Ingenieria de Software <a href="https://github.com/KChinchillaHN/HonduCaribe_IngSoftwareI"> HonduCaribe </a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a class="site_title"><%= image_tag "gota.png", style: "width: 48px"%> HonduCaribe </a>
      </div>
      <div class="clearfix"></div>

      <% if current_user %>
      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Bienvenido,</span>
          <h2>Mr. Jose</h2>
        </div>
      </div>

      <!-- /menu profile quick info -->

      <br />
      <% end %>
      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
          <% if current_user %>
            <h3>General Jose's Managers</h3>
          <% end %>

          <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%= link_to "HonduCaribe", root_path%>
                <% unless current_user %>
                </li>
                <li><%= link_to "Login", login_path %><li>
                  <%= link_to new_user_path do %>
                    <span class="fa fa-address-card-o"></span>
                    Crear Usuario
                  <% end %>
                </li>
                <%  end %>
              </ul>
            </li>

            <% if current_user %>
            <li><a><i class="fa fa-users"></i> Empleados <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%= link_to "Creacion de nuevo Empleado", new_employee_path%>
                </li>
                <li><%= link_to "Listado de Empleados", employees_path%>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-graduation-cap"></i> Capacitaciones <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%= link_to "Listado de Capacitaciones", trainings_path%>
                </li>
                <li><%= link_to "Creacion de nueva Capacitaciones", new_training_path%>
                </li>
                <li><%= link_to "Instituciones", institutions_path%>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-sitemap"></i> Estructura Laboral <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%= link_to "Estructura Laboral", work_structures_path%>
                </li>
                <li><%= link_to "Crear Habilidad", new_ability_path%>
                </li>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3>Reportes</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-users"></i> Reporte de Empleados <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                  <li><%= link_to "Bono Educativo", bonoEducativo_path %> </li>
                <li><%= link_to "Reporte de Horas", hours_path%>
                </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <% if current_user %>
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag "img.jpg" %>Mr Jose
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;">  Perfil</a>
            </li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">100%</span>
                <span>Configuraciones</span>
              </a>
            </li>
            <li>
              <a href="javascript:;">Ayuda</a>
          <li>
            <%= link_to logout_path, data: {method: :delete} do %>
            <span class="fa fa-sign-out"></span> 
            Cerrar Sesion 
            <% end %>
          </li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>Mr Jose Maria</span>
                      <span class="time">28-Febrero-2016</span>
                      </span>
                      <span class="message">
                                        Recordatoio sobre la capacitacion de los empleados
                                        de HonduCaribe. Recuerda que ...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                                     <span>Mr Jose Maria</span>
                      <span class="time">30-Abril-2017</span>
                      </span>
                      <span class="message">
                                        Recordatoio sobre la capacitacion de los empleados
                                        de HonduCaribe. Recuerda que ...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                     <span>Mr Jose Maria</span>
                      <span class="time">13-Junio-2017</span>
                      </span>
                      <span class="message">
                                        Recordatoio sobre la capacitacion de los empleados
                                        de HonduCaribe. Recuerda que ....
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                     <span>Mr Jose Maria</span>
                      <span class="time">1-Agosto-2017</span>
                      </span>
                      <span class="message">
                                        Recordatoio sobre la capacitacion de los empleados
                                        de HonduCaribe. Recuerda que ...
                                    </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>Ver todos los eventos</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->